import { StatColor } from "./types"

export interface ColorScheme {
    text: string
    iconBg: string
    iconColor: string
    iconHoverBg: string
    topBar: string
    border: string
    hoverBorder: string
    glowShadow: string
    gradientBg: string
    solidBg: string
    progressFill: string
    ambientOrb: string
    badgeBg: string
}

export const COLOR_CONFIGS: Record<StatColor, ColorScheme> = {
    blue: {
        text: "text-blue-600 dark:text-blue-400",
        iconBg: "bg-blue-50 dark:bg-blue-950/60",
        iconColor: "text-blue-600 dark:text-blue-400",
        iconHoverBg: "group-hover:bg-blue-600 group-hover:text-white",
        topBar: "from-blue-600 to-sky-500",
        border: "border-blue-100/80 dark:border-blue-950/60",
        hoverBorder: "hover:border-blue-300 dark:hover:border-blue-800",
        glowShadow: "hover:shadow-blue-500/10",
        gradientBg: "from-blue-50/60 via-background to-background dark:from-blue-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-blue-600 to-sky-700 text-white",
        progressFill: "bg-gradient-to-r from-blue-600 to-sky-500",
        ambientOrb: "bg-blue-500/10",
        badgeBg: "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950/70 dark:text-blue-300 dark:border-blue-800",
    },
    indigo: {
        text: "text-indigo-600 dark:text-indigo-400",
        iconBg: "bg-indigo-50 dark:bg-indigo-950/60",
        iconColor: "text-indigo-600 dark:text-indigo-400",
        iconHoverBg: "group-hover:bg-indigo-600 group-hover:text-white",
        topBar: "from-indigo-600 to-violet-600",
        border: "border-indigo-100/80 dark:border-indigo-950/60",
        hoverBorder: "hover:border-indigo-300 dark:hover:border-indigo-800",
        glowShadow: "hover:shadow-indigo-500/10",
        gradientBg: "from-indigo-50/60 via-background to-background dark:from-indigo-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-indigo-600 to-purple-700 text-white",
        progressFill: "bg-gradient-to-r from-indigo-600 to-violet-500",
        ambientOrb: "bg-indigo-500/10",
        badgeBg: "bg-indigo-50 text-indigo-700 border-indigo-200 dark:bg-indigo-950/70 dark:text-indigo-300 dark:border-indigo-800",
    },
    emerald: {
        text: "text-emerald-600 dark:text-emerald-400",
        iconBg: "bg-emerald-50 dark:bg-emerald-950/60",
        iconColor: "text-emerald-600 dark:text-emerald-400",
        iconHoverBg: "group-hover:bg-emerald-600 group-hover:text-white",
        topBar: "from-emerald-500 to-teal-500",
        border: "border-emerald-100/80 dark:border-emerald-950/60",
        hoverBorder: "hover:border-emerald-300 dark:hover:border-emerald-800",
        glowShadow: "hover:shadow-emerald-500/10",
        gradientBg: "from-emerald-50/60 via-background to-background dark:from-emerald-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-emerald-600 to-teal-700 text-white",
        progressFill: "bg-gradient-to-r from-emerald-500 to-teal-400",
        ambientOrb: "bg-emerald-500/10",
        badgeBg: "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/70 dark:text-emerald-300 dark:border-emerald-800",
    },
    violet: {
        text: "text-purple-600 dark:text-purple-400",
        iconBg: "bg-purple-50 dark:bg-purple-950/60",
        iconColor: "text-purple-600 dark:text-purple-400",
        iconHoverBg: "group-hover:bg-purple-600 group-hover:text-white",
        topBar: "from-purple-600 to-fuchsia-600",
        border: "border-purple-100/80 dark:border-purple-950/60",
        hoverBorder: "hover:border-purple-300 dark:hover:border-purple-800",
        glowShadow: "hover:shadow-purple-500/10",
        gradientBg: "from-purple-50/60 via-background to-background dark:from-purple-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-purple-600 to-pink-700 text-white",
        progressFill: "bg-gradient-to-r from-purple-600 to-fuchsia-500",
        ambientOrb: "bg-purple-500/10",
        badgeBg: "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/70 dark:text-purple-300 dark:border-purple-800",
    },
    amber: {
        text: "text-amber-600 dark:text-amber-400",
        iconBg: "bg-amber-50 dark:bg-amber-950/60",
        iconColor: "text-amber-600 dark:text-amber-400",
        iconHoverBg: "group-hover:bg-amber-500 group-hover:text-white",
        topBar: "from-amber-500 to-orange-500",
        border: "border-amber-100/80 dark:border-amber-950/60",
        hoverBorder: "hover:border-amber-300 dark:hover:border-amber-800",
        glowShadow: "hover:shadow-amber-500/10",
        gradientBg: "from-amber-50/60 via-background to-background dark:from-amber-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-amber-600 to-orange-700 text-white",
        progressFill: "bg-gradient-to-r from-amber-500 to-orange-400",
        ambientOrb: "bg-amber-500/10",
        badgeBg: "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/70 dark:text-amber-300 dark:border-amber-800",
    },
    rose: {
        text: "text-rose-600 dark:text-rose-400",
        iconBg: "bg-rose-50 dark:bg-rose-950/60",
        iconColor: "text-rose-600 dark:text-rose-400",
        iconHoverBg: "group-hover:bg-rose-600 group-hover:text-white",
        topBar: "from-rose-500 to-pink-600",
        border: "border-rose-100/80 dark:border-rose-950/60",
        hoverBorder: "hover:border-rose-300 dark:hover:border-rose-800",
        glowShadow: "hover:shadow-rose-500/10",
        gradientBg: "from-rose-50/60 via-background to-background dark:from-rose-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-rose-600 to-pink-700 text-white",
        progressFill: "bg-gradient-to-r from-rose-500 to-pink-500",
        ambientOrb: "bg-rose-500/10",
        badgeBg: "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/70 dark:text-rose-300 dark:border-rose-800",
    },
    cyan: {
        text: "text-cyan-600 dark:text-cyan-400",
        iconBg: "bg-cyan-50 dark:bg-cyan-950/60",
        iconColor: "text-cyan-600 dark:text-cyan-400",
        iconHoverBg: "group-hover:bg-cyan-600 group-hover:text-white",
        topBar: "from-cyan-500 to-blue-500",
        border: "border-cyan-100/80 dark:border-cyan-950/60",
        hoverBorder: "hover:border-cyan-300 dark:hover:border-cyan-800",
        glowShadow: "hover:shadow-cyan-500/10",
        gradientBg: "from-cyan-50/60 via-background to-background dark:from-cyan-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-cyan-600 to-blue-700 text-white",
        progressFill: "bg-gradient-to-r from-cyan-500 to-blue-500",
        ambientOrb: "bg-cyan-500/10",
        badgeBg: "bg-cyan-50 text-cyan-700 border-cyan-200 dark:bg-cyan-950/70 dark:text-cyan-300 dark:border-cyan-800",
    },
    fuchsia: {
        text: "text-fuchsia-600 dark:text-fuchsia-400",
        iconBg: "bg-fuchsia-50 dark:bg-fuchsia-950/60",
        iconColor: "text-fuchsia-600 dark:text-fuchsia-400",
        iconHoverBg: "group-hover:bg-fuchsia-600 group-hover:text-white",
        topBar: "from-fuchsia-500 to-pink-500",
        border: "border-fuchsia-100/80 dark:border-fuchsia-950/60",
        hoverBorder: "hover:border-fuchsia-300 dark:hover:border-fuchsia-800",
        glowShadow: "hover:shadow-fuchsia-500/10",
        gradientBg: "from-fuchsia-50/60 via-background to-background dark:from-fuchsia-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-fuchsia-600 to-rose-700 text-white",
        progressFill: "bg-gradient-to-r from-fuchsia-500 to-pink-500",
        ambientOrb: "bg-fuchsia-500/10",
        badgeBg: "bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200 dark:bg-fuchsia-950/70 dark:text-fuchsia-300 dark:border-fuchsia-800",
    },
    teal: {
        text: "text-teal-600 dark:text-teal-400",
        iconBg: "bg-teal-50 dark:bg-teal-950/60",
        iconColor: "text-teal-600 dark:text-teal-400",
        iconHoverBg: "group-hover:bg-teal-600 group-hover:text-white",
        topBar: "from-teal-500 to-emerald-500",
        border: "border-teal-100/80 dark:border-teal-950/60",
        hoverBorder: "hover:border-teal-300 dark:hover:border-teal-800",
        glowShadow: "hover:shadow-teal-500/10",
        gradientBg: "from-teal-50/60 via-background to-background dark:from-teal-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-teal-600 to-emerald-700 text-white",
        progressFill: "bg-gradient-to-r from-teal-500 to-emerald-400",
        ambientOrb: "bg-teal-500/10",
        badgeBg: "bg-teal-50 text-teal-700 border-teal-200 dark:bg-teal-950/70 dark:text-teal-300 dark:border-teal-800",
    },
    orange: {
        text: "text-orange-600 dark:text-orange-400",
        iconBg: "bg-orange-50 dark:bg-orange-950/60",
        iconColor: "text-orange-600 dark:text-orange-400",
        iconHoverBg: "group-hover:bg-orange-600 group-hover:text-white",
        topBar: "from-orange-500 to-amber-500",
        border: "border-orange-100/80 dark:border-orange-950/60",
        hoverBorder: "hover:border-orange-300 dark:hover:border-orange-800",
        glowShadow: "hover:shadow-orange-500/10",
        gradientBg: "from-orange-50/60 via-background to-background dark:from-orange-950/20 dark:via-background dark:to-background",
        solidBg: "bg-gradient-to-br from-orange-600 to-amber-700 text-white",
        progressFill: "bg-gradient-to-r from-orange-500 to-amber-400",
        ambientOrb: "bg-orange-500/10",
        badgeBg: "bg-orange-50 text-orange-700 border-orange-200 dark:bg-orange-950/70 dark:text-orange-300 dark:border-orange-800",
    },
}
