import type { OrderDispatch } from "./types"

export const mockDispatches: OrderDispatch[] = [
  {
    id: "disp-9281",
    orderId: "ord-9281",
    orderNumber: "ORD-9281",
    clientName: "Dr. Aris Varma",
    warehouseName: "Mumbai Central Warehouse",
    warehouseCode: "MUM-CW",
    shippingAddress: "12 Medical Plaza, Andheri East, Mumbai, Maharashtra 400069",
    packedAt: "2026-05-28T10:35:00.000Z",
    partnerName: "",
    partnerService: "",
    trackingNumber: "",
    dispatchDate: "2026-05-28",
    expectedDeliveryDate: "2026-05-30",
    packageCount: 1,
    grossWeightKg: 3.2,
    freightPaymentMode: "Included",
    status: "Ready",
    challanNumber: "CH-9281",
    invoiceNumber: "INV-9281",
    items: [
      { id: "di-1", productName: "Surgical Blade #10", sku: "SB-010-G", quantity: 6 },
      { id: "di-2", productName: "Medical Gauze", sku: "MG-ST-100", quantity: 4 },
      { id: "di-3", productName: "Antiseptic Solution", sku: "AS-500", quantity: 2 },
    ],
    timeline: [
      {
        id: "tl-1",
        label: "Outward completed",
        description: "Warehouse scan validation completed.",
        timestamp: "2026-05-28T10:35:00.000Z",
        status: "complete",
      },
      {
        id: "tl-2",
        label: "Dispatch details pending",
        description: "Delivery partner and tracking number need to be recorded.",
        timestamp: "2026-05-28T10:40:00.000Z",
        status: "current",
      },
    ],
  },
  {
    id: "disp-9282",
    orderId: "ord-9282",
    orderNumber: "ORD-9282",
    clientName: "City Dental Clinic",
    warehouseName: "Pune Hub",
    warehouseCode: "PUN-HB",
    shippingAddress: "44 Koregaon Park Road, Pune, Maharashtra 411001",
    packedAt: "2026-05-28T09:50:00.000Z",
    partnerName: "Delhivery",
    partnerService: "Surface Express",
    trackingNumber: "DLV92824421",
    dispatchDate: "2026-05-28",
    expectedDeliveryDate: "2026-05-31",
    packageCount: 2,
    grossWeightKg: 6.4,
    freightCharges: 420,
    freightPaymentMode: "Paid",
    status: "Dispatched",
    challanNumber: "CH-9282",
    invoiceNumber: "INV-9282",
    shippingLabelRef: "LBL-DLV92824421",
    remarks: "Keep upright during transport.",
    items: [
      { id: "di-4", productName: "Latex Examination Gloves", sku: "LEG-M-100", quantity: 10 },
      { id: "di-5", productName: "Dental Bibs", sku: "DB-BL-50", quantity: 8 },
    ],
    timeline: [
      {
        id: "tl-3",
        label: "Outward completed",
        description: "All products packed and validated.",
        timestamp: "2026-05-28T09:50:00.000Z",
        status: "complete",
      },
      {
        id: "tl-4",
        label: "Shipment booked",
        description: "Tracking DLV92824421 recorded with Delhivery.",
        timestamp: "2026-05-28T10:10:00.000Z",
        status: "current",
      },
    ],
  },
  {
    id: "disp-9283",
    orderId: "ord-9283",
    orderNumber: "ORD-9283",
    clientName: "Shree Eye Care",
    warehouseName: "Mumbai Central Warehouse",
    warehouseCode: "MUM-CW",
    shippingAddress: "Unit 8, Linking Road, Bandra West, Mumbai, Maharashtra 400050",
    packedAt: "2026-05-28T08:20:00.000Z",
    partnerName: "Porter",
    partnerService: "Same Day",
    trackingNumber: "PTR-55109",
    dispatchDate: "2026-05-28",
    expectedDeliveryDate: "2026-05-28",
    packageCount: 1,
    grossWeightKg: 2.1,
    freightPaymentMode: "To Pay",
    vehicleNumber: "MH 02 AB 4401",
    driverName: "Ramesh K.",
    driverPhone: "9876543210",
    status: "In Transit",
    challanNumber: "CH-9283",
    invoiceNumber: "INV-9283",
    items: [
      { id: "di-6", productName: "Eye Drape", sku: "ED-FEN-01", quantity: 5 },
      { id: "di-7", productName: "Sterile Syringe", sku: "SS-10ML", quantity: 20 },
    ],
    timeline: [
      {
        id: "tl-5",
        label: "Outward completed",
        description: "Urgent dispatch packed by Mumbai warehouse.",
        timestamp: "2026-05-28T08:20:00.000Z",
        status: "complete",
      },
      {
        id: "tl-6",
        label: "Picked up",
        description: "Porter partner picked up package.",
        timestamp: "2026-05-28T08:45:00.000Z",
        status: "current",
      },
    ],
  },
  {
    id: "disp-9279",
    orderId: "ord-9279",
    orderNumber: "ORD-9279",
    clientName: "Prime Medical Supplies",
    warehouseName: "Delhi North Depot",
    warehouseCode: "DEL-ND",
    shippingAddress: "B-14 Industrial Area, Delhi 110052",
    packedAt: "2026-05-27T16:20:00.000Z",
    partnerName: "Blue Dart",
    partnerService: "Priority",
    trackingNumber: "BD92790018",
    dispatchDate: "2026-05-27",
    expectedDeliveryDate: "2026-05-29",
    packageCount: 3,
    grossWeightKg: 8.8,
    freightCharges: 780,
    freightPaymentMode: "Paid",
    status: "Delivered",
    challanNumber: "CH-9279",
    invoiceNumber: "INV-9279",
    ewayBillNumber: "EWB-9279-551",
    items: [
      { id: "di-8", productName: "Disposable Mask", sku: "DM-3P-50", quantity: 12 },
    ],
    timeline: [
      {
        id: "tl-7",
        label: "Dispatched",
        description: "Shipment handed over to Blue Dart.",
        timestamp: "2026-05-27T17:00:00.000Z",
        status: "complete",
      },
      {
        id: "tl-8",
        label: "Delivered",
        description: "Delivery confirmed by client receiving desk.",
        timestamp: "2026-05-28T13:30:00.000Z",
        status: "complete",
      },
    ],
  },
]

export function getMockDispatch(id: string) {
  return mockDispatches.find((dispatch) => dispatch.id === id || dispatch.orderId === id) ?? null
}
