import type { OutwardOrder } from "./types"

export const mockOutwardOrders: OutwardOrder[] = [
  {
    id: "ord-9281",
    orderNumber: "ORD-9281",
    clientName: "Dr. Aris Varma",
    warehouseName: "Mumbai Central Warehouse",
    warehouseCode: "MUM-CW",
    shippingAddress: "12 Medical Plaza, Andheri East, Mumbai, Maharashtra 400069",
    orderDate: "2026-05-27",
    promisedDate: "2026-05-30",
    status: "Ready",
    priority: "High",
    pickerName: "Warehouse User",
    items: [
      {
        id: "oi-1",
        productId: "p-1001",
        productName: "Surgical Blade #10",
        variantName: "Sterile Pack",
        sku: "SB-010-G",
        barcode: "8901450000101",
        orderedQty: 6,
        scannedQty: 0,
        locationCode: "A1-R2-S3",
      },
      {
        id: "oi-2",
        productId: "p-1002",
        productName: "Medical Gauze",
        variantName: "100 pcs",
        sku: "MG-ST-100",
        barcode: "8901450000217",
        orderedQty: 4,
        scannedQty: 0,
        locationCode: "A1-R3-S1",
      },
      {
        id: "oi-3",
        productId: "p-1003",
        productName: "Antiseptic Solution",
        variantName: "500 ml",
        sku: "AS-500",
        barcode: "8901450000453",
        orderedQty: 2,
        scannedQty: 0,
        locationCode: "B2-R1-S2",
      },
    ],
    scanHistory: [],
  },
  {
    id: "ord-9282",
    orderNumber: "ORD-9282",
    clientName: "City Dental Clinic",
    warehouseName: "Pune Hub",
    warehouseCode: "PUN-HB",
    shippingAddress: "44 Koregaon Park Road, Pune, Maharashtra 411001",
    orderDate: "2026-05-26",
    promisedDate: "2026-05-29",
    status: "Partially Scanned",
    priority: "Normal",
    pickerName: "Meera S.",
    items: [
      {
        id: "oi-4",
        productId: "p-2001",
        productName: "Latex Examination Gloves",
        variantName: "Medium",
        sku: "LEG-M-100",
        barcode: "8901450000637",
        orderedQty: 10,
        scannedQty: 6,
        locationCode: "C1-R2-S1",
      },
      {
        id: "oi-5",
        productId: "p-2002",
        productName: "Dental Bibs",
        variantName: "Blue Pack",
        sku: "DB-BL-50",
        barcode: "8901450000712",
        orderedQty: 8,
        scannedQty: 8,
        locationCode: "C1-R4-S4",
      },
    ],
    scanHistory: [
      {
        id: "scan-1",
        barcode: "8901450000712",
        productName: "Dental Bibs",
        message: "Dental Bibs completed",
        type: "success",
        timestamp: "2026-05-28T09:40:00.000Z",
      },
      {
        id: "scan-2",
        barcode: "8901450000637",
        productName: "Latex Examination Gloves",
        message: "6 of 10 gloves scanned",
        type: "success",
        timestamp: "2026-05-28T09:43:00.000Z",
      },
    ],
  },
  {
    id: "ord-9283",
    orderNumber: "ORD-9283",
    clientName: "Shree Eye Care",
    warehouseName: "Mumbai Central Warehouse",
    warehouseCode: "MUM-CW",
    shippingAddress: "Unit 8, Linking Road, Bandra West, Mumbai, Maharashtra 400050",
    orderDate: "2026-05-25",
    promisedDate: "2026-05-28",
    status: "Exception",
    priority: "Urgent",
    pickerName: "Nikhil P.",
    items: [
      {
        id: "oi-6",
        productId: "p-3001",
        productName: "Eye Drape",
        variantName: "Fenestrated",
        sku: "ED-FEN-01",
        barcode: "8901450000880",
        orderedQty: 5,
        scannedQty: 3,
        locationCode: "D3-R1-S2",
      },
      {
        id: "oi-7",
        productId: "p-3002",
        productName: "Sterile Syringe",
        variantName: "10 ml",
        sku: "SS-10ML",
        barcode: "8901450000941",
        orderedQty: 20,
        scannedQty: 0,
        locationCode: "D3-R2-S5",
      },
    ],
    scanHistory: [
      {
        id: "scan-3",
        barcode: "UNKNOWN-442",
        message: "Barcode not found in this order",
        type: "error",
        timestamp: "2026-05-28T10:05:00.000Z",
      },
    ],
  },
  {
    id: "ord-9279",
    orderNumber: "ORD-9279",
    clientName: "Prime Medical Supplies",
    warehouseName: "Delhi North Depot",
    warehouseCode: "DEL-ND",
    shippingAddress: "B-14 Industrial Area, Delhi 110052",
    orderDate: "2026-05-24",
    promisedDate: "2026-05-28",
    status: "Completed",
    priority: "Normal",
    pickerName: "Ankit R.",
    items: [
      {
        id: "oi-8",
        productId: "p-4001",
        productName: "Disposable Mask",
        variantName: "3 Ply",
        sku: "DM-3P-50",
        barcode: "8901450001054",
        orderedQty: 12,
        scannedQty: 12,
        locationCode: "E1-R1-S1",
      },
    ],
    scanHistory: [
      {
        id: "scan-4",
        barcode: "8901450001054",
        productName: "Disposable Mask",
        message: "Order outward completed",
        type: "success",
        timestamp: "2026-05-28T08:30:00.000Z",
      },
    ],
  },
]

export function getMockOutwardOrder(id: string) {
  return mockOutwardOrders.find((order) => order.id === id) ?? null
}
